markdown: rdiscount
pygments: true
permalink: pretty
lsi: true
future:      true

exclude:     ['_assets', '_src', 'README.md', 'Gemfile', 'Gemfile.lock', 'package.json', 'Makefile']
##################
# JSBuild Plugin #
##################

jsbuild:
  hooks: _plugins/tools/hooks/jsbuild.hook

  # Compile the third-party TypeScript files first
  # and save them at _src/_js
  # "../_src/_js/some-framework.js":
  #   hooks: _plugins/tools/hooks/typescript.rb
  #   include:
  #     - _assets/vendor/some-framework/module.ts
  # Now we can use the compiled TypeScript files.
  js/main-@hash.js:
    - _src/js/libs/*.js
    - _src/js/main.js
  js/main.js:
    - _src/js/libs/*.js
    - _src/js/main.js

####################
# LessBuild Plugin #
####################

lessbuild:
  hooks: _plugins/tools/hooks/lessbuild.hook

  css/main-@hash.css:
    main: _src/less/site.less
    include:
      - _src/less/*.less
      - { bootstrap: _src/bootstrap/*.less }
  css/main.css:
    main: _src/less/site.less
    include:
      - _src/less/*.less
      - { bootstrap: _src/bootstrap/*.less }

###############
# Copy Plugin #
###############

copy:
  page[0-9]/docs:
    - _assets/*.txt
  img:
    - _assets/bootstrap/img/*.*


# TEST #
tools:
  defaults:
    jsbuild:
      hooks: ../_plugins/tools/hooks/jsbuild.hook
    lessbuild:
      hooks: ../_plugins/tools/hooks/lessbuild.hook
  tasks:
    - jsbuild:
      "../_src/_js/some-framework.js":
        hooks: _src/hooks/typescript.rb
        include:
          - _assets/vendor/some-framework/module.ts
      js/main-@hash.js:
        - _src/_js/some-framework.js
        - _src/js/main.js
    - lessbuild:
      css/main-@hash.css:
        main: _src/less/main.less
        include:
          - _src/less/*.less
          - { bootstrap: _assets/node_modules/bootstrap/less/*.less }
    - jsbuild:
      js/main.js:
        - _src/_js/some-framework.js
        - _src/js/main.js
    - lessbuild:
      css/main.css:
        main: _src/less/main.less
        include:
          - _src/less/*.less
          - { bootstrap: _assets/node_modules/bootstrap/less/*.less }
    - copy:
      page[0-9]/docs:
        - _assets/*.txt
      img:
        - _assets/node_modules/bootstrap/img/*.*