// Generated by CoffeeScript 1.4.0
(function() {

    window.App = Ember.Application.create();
    App.Router = Ember.Router.extend();
    App.Router.map(function(match) {
        /*match('/').to('application', function(match){

        });*/
        match('/').to('index')
        match('/home').to('home')
        match('/table').to('table')
        match('/posts').to('posts')
        match('/posts/:post_id').to('post');
        /*, function(match) {
            match('/:post_id').to('post', function(match) {
              match('/').to('postIndex');
              match('/comments').to('comments');
              match('/comments/:comment_id').to('comment');
            });
          });*/
        
    });


    App.PostsRoute = Ember.Route.extend({
        setupController: function(controller,model) {
            setTimeout(function(){
                controller.set('isLoaded', true);
                controller.set('posts',dataposts.posts)
            },150)
        }
    });

    App.PostRoute = Ember.Route.extend({
        renderTemplate: function() {
            this.render('post',{  'outlet':'post' });
        },
        model: function(params) {
            return dataposts.posts[params.post_id-1]
        }    
    });

    App.IndexRoute = Ember.Route.extend({
        setupController: function(controller,model) {
            controller.set('hours', [
              "Monday through Friday: 9am to 5pm",
              "Saturday: Noon to Midnight",
              "Sunday: Noon to 6pm"
            ])
        }
    });

    App.HomeRoute = Ember.Route.extend({
        setupController: function(controller,model) {
            controller.set('hours', [
              "Monday through Friday: 9am to 5pm",
              "Saturday: Noon to Midnight",
              "Sunday: Noon to 6pm"
            ])
        }
    });

    App.TableRoute = Ember.Route.extend({
        setupController: function(controller,model) {
            controller.set('numRows',5000)
        }
    });

    App.TableController = Ember.Controller.extend({
        tableController: Ember.computed(function() {
          return Ember.get('App.TableSimpleExample.TableController').create();
        }).property()
    });

  /*App.ApplicationView = Ember.View.extend({
    classNames: 'ember-app',
    templateName: 'application'
  });

  

    */
  App.initialize();



  var dataposts = {
      posts:[
          {'id':1, 'title':'titre1', 'content':'contenu1'},
          {'id':2, 'title':'titre2', 'content':'contenu2'},
          {'id':3, 'title':'titre3', 'content':'contenu3'},
          {'id':4, 'title':'titre4', 'content':'contenu4'},
      ]
  
  };

  var datacomments = {
      comments:[
          {'id':1, 'pid':1, 'content':'commentaire 1'},
      ]
  }


}).call(this);
